var _w_d_payment_8h =
[
    [ "WDPaymentReference", "interface_w_d_payment_reference.html", "interface_w_d_payment_reference" ],
    [ "WDPaymentCore", "interface_w_d_payment_core.html", "interface_w_d_payment_core" ],
    [ "WDPayment", "interface_w_d_payment.html", "interface_w_d_payment" ],
    [ "WDPaymentRefund", "interface_w_d_payment_refund.html", "interface_w_d_payment_refund" ],
    [ "WDPaymentRefundCard", "interface_w_d_payment_refund_card.html", "interface_w_d_payment_refund_card" ],
    [ "WDPaymentRefundCash", "interface_w_d_payment_refund_cash.html", "interface_w_d_payment_refund_cash" ],
    [ "WDPaymentRefundWeChat", "interface_w_d_payment_refund_we_chat.html", "interface_w_d_payment_refund_we_chat" ],
    [ "WDPaymentRefundAlipay", "interface_w_d_payment_refund_alipay.html", "interface_w_d_payment_refund_alipay" ],
    [ "WDPaymentRefundCardCapture", "interface_w_d_payment_refund_card_capture.html", "interface_w_d_payment_refund_card_capture" ],
    [ "WDPaymentReverse", "interface_w_d_payment_reverse.html", "interface_w_d_payment_reverse" ],
    [ "WDPaymentReverseCard", "interface_w_d_payment_reverse_card.html", null ],
    [ "WDPaymentReverseCash", "interface_w_d_payment_reverse_cash.html", null ],
    [ "WDPaymentReverseWeChat", "interface_w_d_payment_reverse_we_chat.html", null ],
    [ "WDPaymentReverseAlipay", "interface_w_d_payment_reverse_alipay.html", null ],
    [ "WDPaymentReverseCardCapture", "interface_w_d_payment_reverse_card_capture.html", null ],
    [ "WDPaymentCapture", "interface_w_d_payment_capture.html", "interface_w_d_payment_capture" ],
    [ "WDPaymentCaptureCard", "interface_w_d_payment_capture_card.html", null ],
    [ "WDPaymentPreAuthorizeSupplement", "interface_w_d_payment_pre_authorize_supplement.html", "interface_w_d_payment_pre_authorize_supplement" ],
    [ "WDPaymentPreAuthorizeSupplementCard", "interface_w_d_payment_pre_authorize_supplement_card.html", "interface_w_d_payment_pre_authorize_supplement_card" ],
    [ "NS_ENUM", "_w_d_payment_8h.html#a523c51252451ffbd9c64cb5df8d3b8aa", null ],
    [ "NS_ENUM", "_w_d_payment_8h.html#afb8e38112df5e17ddf482e77973d099d", null ],
    [ "NS_ENUM", "_w_d_payment_8h.html#a179f8453bff7892486e6a9d59e764a09", null ]
];