var annotated_dup =
[
    [ "WDAError", "interface_w_d_a_error.html", null ],
    [ "WDBarCodeType", "interface_w_d_bar_code_type.html", "interface_w_d_bar_code_type" ],
    [ "WDCashDrawerManager", "interface_w_d_cash_drawer_manager.html", "interface_w_d_cash_drawer_manager" ],
    [ "WDCashManager", "interface_w_d_cash_manager.html", "interface_w_d_cash_manager" ],
    [ "WDCustomerManager", "interface_w_d_customer_manager.html", "interface_w_d_customer_manager" ],
    [ "WDEnvironmentConfiguration", "interface_w_d_environment_configuration.html", "interface_w_d_environment_configuration" ],
    [ "WDePOS", "interface_w_de_p_o_s.html", "interface_w_de_p_o_s" ],
    [ "<WDePOSDelegate >", "protocol_w_de_p_o_s_delegate_01-p.html", "protocol_w_de_p_o_s_delegate_01-p" ],
    [ "WDError", "class_w_d_error.html", null ],
    [ "WDExtensionManager", "interface_w_d_extension_manager.html", "interface_w_d_extension_manager" ],
    [ "<WDManagerDelegate >", "protocol_w_d_manager_delegate_01-p.html", "protocol_w_d_manager_delegate_01-p" ],
    [ "WDObject", "interface_w_d_object.html", "interface_w_d_object" ],
    [ "<WDPaymentDelegate >", "protocol_w_d_payment_delegate_01-p.html", "protocol_w_d_payment_delegate_01-p" ],
    [ "WDPrinterManager", "interface_w_d_printer_manager.html", "interface_w_d_printer_manager" ],
    [ "<WDPrinting >", "protocol_w_d_printing_01-p.html", "protocol_w_d_printing_01-p" ],
    [ "WDProductAvailability", "interface_w_d_product_availability.html", "interface_w_d_product_availability" ],
    [ "WDProductCatalogue", "interface_w_d_product_catalogue.html", "interface_w_d_product_catalogue" ],
    [ "WDProductCatalogueCategory", "interface_w_d_product_catalogue_category.html", "interface_w_d_product_catalogue_category" ],
    [ "WDProductCatalogueCore", "interface_w_d_product_catalogue_core.html", "interface_w_d_product_catalogue_core" ],
    [ "WDProductCatalogueDiscount", "interface_w_d_product_catalogue_discount.html", "interface_w_d_product_catalogue_discount" ],
    [ "WDProductCatalogueManager", "interface_w_d_product_catalogue_manager.html", "interface_w_d_product_catalogue_manager" ],
    [ "WDProductCatalogueProduct", "interface_w_d_product_catalogue_product.html", "interface_w_d_product_catalogue_product" ],
    [ "WDProductPrice", "interface_w_d_product_price.html", "interface_w_d_product_price" ],
    [ "WDProductStock", "interface_w_d_product_stock.html", "interface_w_d_product_stock" ],
    [ "WDReceipt", "interface_w_d_receipt.html", "interface_w_d_receipt" ],
    [ "WDReceiptAlipayDetails", "interface_w_d_receipt_alipay_details.html", "interface_w_d_receipt_alipay_details" ],
    [ "WDReceiptData", "interface_w_d_receipt_data.html", "interface_w_d_receipt_data" ],
    [ "WDReceiptItem", "interface_w_d_receipt_item.html", "interface_w_d_receipt_item" ],
    [ "WDReceiptMerchant", "interface_w_d_receipt_merchant.html", "interface_w_d_receipt_merchant" ],
    [ "WDReceiptPaymentItem", "interface_w_d_receipt_payment_item.html", "interface_w_d_receipt_payment_item" ],
    [ "WDReceiptTaxSummary", "interface_w_d_receipt_tax_summary.html", "interface_w_d_receipt_tax_summary" ],
    [ "WDReceiptWeChatDetails", "interface_w_d_receipt_we_chat_details.html", "interface_w_d_receipt_we_chat_details" ],
    [ "WDSale", "interface_w_d_sale.html", "interface_w_d_sale" ],
    [ "WDSaleCoupon", "interface_w_d_sale_coupon.html", "interface_w_d_sale_coupon" ],
    [ "WDSaleFlatDiscount", "interface_w_d_sale_flat_discount.html", "interface_w_d_sale_flat_discount" ],
    [ "WDSaleItem", "interface_w_d_sale_item.html", "interface_w_d_sale_item" ],
    [ "WDSaleItemCore", "interface_w_d_sale_item_core.html", "interface_w_d_sale_item_core" ],
    [ "WDSaleManager", "interface_w_d_sale_manager.html", "interface_w_d_sale_manager" ],
    [ "WDSaleRequest", "interface_w_d_sale_request.html", "interface_w_d_sale_request" ],
    [ "WDSaleResponse", "interface_w_d_sale_response.html", "interface_w_d_sale_response" ],
    [ "WDSaleServiceCharge", "interface_w_d_sale_service_charge.html", "interface_w_d_sale_service_charge" ],
    [ "WDSaleSummaryItem", "interface_w_d_sale_summary_item.html", "interface_w_d_sale_summary_item" ],
    [ "WDScannerManager", "interface_w_d_scanner_manager.html", "interface_w_d_scanner_manager" ],
    [ "<WDScanning >", "protocol_w_d_scanning_01-p.html", "protocol_w_d_scanning_01-p" ],
    [ "WDSSessionManagerCredentials", "interface_w_d_s_session_manager_credentials.html", "interface_w_d_s_session_manager_credentials" ],
    [ "WDTerminalManager", "interface_w_d_terminal_manager.html", "interface_w_d_terminal_manager" ],
    [ "WDUpdateableExtensionManager", "interface_w_d_updateable_extension_manager.html", "interface_w_d_updateable_extension_manager" ],
    [ "WDUserManager", "interface_w_d_user_manager.html", "interface_w_d_user_manager" ],
    [ "WDUtils", "interface_w_d_utils.html", null ],
    [ "WDZReport", "interface_w_d_z_report.html", "interface_w_d_z_report" ],
    [ "WDZReportCategory", "interface_w_d_z_report_category.html", "interface_w_d_z_report_category" ],
    [ "WDZReportCategoryItem", "interface_w_d_z_report_category_item.html", "interface_w_d_z_report_category_item" ]
];